### ISSUE TITLE
Adicionar arquivo de licença GPL ao repositório

### ISSUE THREAD

**Issue by hamc** [fatec-20245/fatec-5sem#10]
O projeto precisa de um arquivo de licença GPL para definir claramente os termos de uso, modificação e distribuição do código. Adicionar o arquivo de licença GPL ajudará a proteger os direitos de autor e esclarecerá as permissões para os contribuidores e usuários do projeto.

Adicionar um arquivo LICENSE na raiz do repositório contendo o texto da Licença Pública Geral GNU (GPL).

**Comment by danieloliveira017** [comment]
Issues resolvida sobre GLP
