### ISSUE TITLE
Criar nova página HTML com formulário de cadastro de usuário

### ISSUE THREAD

**Issue by hamc** [fatec-20245/fatec-5sem#7]
Necessário adicionar uma nova página HTML com um formulário para cadastro de novos usuários. O formulário deve incluir campos para coletar informações essenciais como nome, e-mail, senha e confirmação de senha, garantindo uma interface simples e intuitiva para o usuário.

**Comment by Joshua-Vankayalapati** [comment]
Olá Posso criar uma página de formulário de inscrição para você. Por favor, verifique esta imagem. Ele se alinha com o que você está imaginando para o seu projeto. Estou usando o tradutor para conversar com você. Peço desculpas se houver alguma confusão sobre o que estou enviando mensagens aqui. Eu ficaria feliz em assumir seu projeto, se você quiser, e criar a página de registro para você. Atribua-me ao seu projeto se estiver interessado!

![registration and login demo](https://github.com/user-attachments/assets/2243cce2-b083-4932-b35b-efda8c0a557e)
